#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (51.69%)
# Total Accepted:    113.5K
# Total Submissions: 219.6K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dist_s = {}
        dist_t = {}

        for i in s:
            if i not in dist_s:
                dist_s[i] = 1
            else:
                dist_s[i] += 1
        
        for j in t:
            if j not in dist_t:
                dist_t[j] = 1
            else:
                dist_t[j] += 1

        for j in dist_t:
            if j not in dist_s:
                return j
            elif dist_t[j] != dist_s[j]:
                return j

if __name__ == "__main__":
    print(Solution().findTheDifference("a",'aa'))

        
